

```
## CERTIFICATE GENERATOR

```

In [2]:
# install external package 'reportlab' because it is not in normal python
# to link pdf to python program
!pip install reportlab

Collecting reportlab
  Downloading reportlab-4.5.1-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.7)
Downloading reportlab-4.5.1-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 33.1 MB/s eta 0:00:00
Installing collected packages: reportlab
Successfully installed reportlab-4.5.1

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import numpy as np
import pandas as pd

from reportlab.lib.pagesizes import landscape , A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

In [5]:
df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)/dataset.xlsx")
df

                  Name                 Course   CourseLevel       Date
0   Christy Cunningham                 Python      Beginner 2023-09-10
1       Douglas Tucker                 PYTHON       MASTER  2023-09-11
2       Travis Walters                   Java  Intermediate 2023-09-12
3     Nathaniel Harris        Web Development      Advanced 2023-09-13
4                    -                    NaN      Advanced        NaT
5         Tonya Carter  AI & Machine Learning      Beginner 2023-09-14
6           Erik Smith     Mobile Development      Beginner 2023-09-15
7   Kristopher Johnson                 Python      Beginner 2023-09-16
8      Jonathan Bucker                    NaN           NaN        NaT
9          Robert Buck                 PYTHON       Master  2023-09-17
10     Joseph Mcdonald                   Java  Intermediate 2023-09-18
11       Jerome Abbott        Web Development      Advanced 2023-09-19
12       William Riley  AI & Machine Learning      Beginner 2023-09-20

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         13 non-null     object
 1   Course       11 non-null     object
 2   CourseLevel  12 non-null     object
 3   Date         11 non-null     datetime64[ns]
dtypes: datetime64[ns](1), object(3)
memory usage: 548.0+ bytes

# Data Cleaning

# Data analysis

In [7]:

df

                  Name                 Course   CourseLevel       Date
0   Christy Cunningham                 Python      Beginner 2023-09-10
1       Douglas Tucker                 PYTHON       MASTER  2023-09-11
2       Travis Walters                   Java  Intermediate 2023-09-12
3     Nathaniel Harris        Web Development      Advanced 2023-09-13
4                    -                    NaN      Advanced        NaT
5         Tonya Carter  AI & Machine Learning      Beginner 2023-09-14
6           Erik Smith     Mobile Development      Beginner 2023-09-15
7   Kristopher Johnson                 Python      Beginner 2023-09-16
8      Jonathan Bucker                    NaN           NaN        NaT
9          Robert Buck                 PYTHON       Master  2023-09-17
10     Joseph Mcdonald                   Java  Intermediate 2023-09-18
11       Jerome Abbott        Web Development      Advanced 2023-09-19
12       William Riley  AI & Machine Learning      Beginner 2023-09-20

In [8]:
# 3 problems with the original dataset
# 1. Inconsistency formatting in "Course" and "Courselevel" columns
# 2. Date format (yyyy-mm-dd)--> change into (dd-mm-yyyy)
# 3. Empty rows (half-empty rows)

In [9]:
df = df.dropna()
df

                  Name                 Course   CourseLevel       Date
0   Christy Cunningham                 Python      Beginner 2023-09-10
1       Douglas Tucker                 PYTHON       MASTER  2023-09-11
2       Travis Walters                   Java  Intermediate 2023-09-12
3     Nathaniel Harris        Web Development      Advanced 2023-09-13
5         Tonya Carter  AI & Machine Learning      Beginner 2023-09-14
6           Erik Smith     Mobile Development      Beginner 2023-09-15
7   Kristopher Johnson                 Python      Beginner 2023-09-16
9          Robert Buck                 PYTHON       Master  2023-09-17
10     Joseph Mcdonald                   Java  Intermediate 2023-09-18
11       Jerome Abbott        Web Development      Advanced 2023-09-19
12       William Riley  AI & Machine Learning      Beginner 2023-09-20

In [10]:
df['Date'][0]

Timestamp('2023-09-10 00:00:00')

In [11]:
# iloc() to access the indexing
df['Date'].iloc[0]

Timestamp('2023-09-10 00:00:00')

In [12]:
# create a new column "FormattedDate"
df["FormattedDate"] = df["Date"].dt.strftime("%d/%m/%Y")
df

/tmp/ipykernel_1124/928631476.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["FormattedDate"] = df["Date"].dt.strftime("%d/%m/%Y")

,Name,Course,CourseLevel,Date,FormattedDate
0,Christy Cunningham,Python,Beginner,2023-09-10,10/09/2023
1,Douglas Tucker,PYTHON,MASTER,2023-09-11,11/09/2023
2,Travis Walters,Java,Intermediate,2023-09-12,12/09/2023
3,Nathaniel Harris,Web Development,Advanced,2023-09-13,13/09/2023
5,Tonya Carter,AI & Machine Learning,Beginner,2023-09-14,14/09/2023
6,Erik Smith,Mobile Development,Beginner,2023-09-15,15/09/2023
7,Kristopher Johnson,Python,Beginner,2023-09-16,16/09/2023
9,Robert Buck,PYTHON,Master,2023-09-17,17/09/2023
10,Joseph Mcdonald,Java,Intermediate,2023-09-18,18/09/2023
11,Jerome Abbott,Web Development,Advanced,2023-09-19,19/09/2023
12,William Riley,AI & Machine Learning,Beginner,2023-09-20,20/09/2023

In [13]:
df["FormattedDate"].dtype

dtype('O')

In [14]:
df.head()

,Name,Course,CourseLevel,Date,FormattedDate
0,Christy Cunningham,Python,Beginner,2023-09-10,10/09/2023
1,Douglas Tucker,PYTHON,MASTER,2023-09-11,11/09/2023
2,Travis Walters,Java,Intermediate,2023-09-12,12/09/2023
3,Nathaniel Harris,Web Development,Advanced,2023-09-13,13/09/2023
5,Tonya Carter,AI & Machine Learning,Beginner,2023-09-14,14/09/2023

In [15]:
# df = df.drop("Date", axis = 1)
df = df.drop("Date", axis = 1)
df

                  Name                 Course   CourseLevel FormattedDate
0   Christy Cunningham                 Python      Beginner    10/09/2023
1       Douglas Tucker                 PYTHON       MASTER     11/09/2023
2       Travis Walters                   Java  Intermediate    12/09/2023
3     Nathaniel Harris        Web Development      Advanced    13/09/2023
5         Tonya Carter  AI & Machine Learning      Beginner    14/09/2023
6           Erik Smith     Mobile Development      Beginner    15/09/2023
7   Kristopher Johnson                 Python      Beginner    16/09/2023
9          Robert Buck                 PYTHON       Master     17/09/2023
10     Joseph Mcdonald                   Java  Intermediate    18/09/2023
11       Jerome Abbott        Web Development      Advanced    19/09/2023
12       William Riley  AI & Machine Learning      Beginner    20/09/2023

In [16]:
df['Course'] = df['Course'].str.capitalize() # broadcasted to all the rows
df['CourseLevel'] = df['CourseLevel'].str.capitalize()

In [17]:
df.head()

                 Name                 Course   CourseLevel FormattedDate
0  Christy Cunningham                 Python      Beginner    10/09/2023
1      Douglas Tucker                 Python       Master     11/09/2023
2      Travis Walters                   Java  Intermediate    12/09/2023
3    Nathaniel Harris        Web development      Advanced    13/09/2023
5        Tonya Carter  Ai & machine learning      Beginner    14/09/2023

4.Done with basic data analysis

Register Fonts

In [18]:
fonts_path = "/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)/fonts"
# Defining path to the fonds folder

In [19]:
pdfmetrics.registerFont(TTFont('Lora-Bold' ,fonts_path + "/Lora-Bold.ttf"))
pdfmetrics.registerFont(TTFont('Lora-Regular' ,fonts_path + "/Lora-Regular.ttf"))

# TTFont() will need 2 inputs
# 1st input --> what font?
# 2nd input --> where is the file of the font?

5.Creating Certificate Generator Logic Function

Version 1 of the function

In [20]:
df.head()

                 Name                 Course   CourseLevel FormattedDate
0  Christy Cunningham                 Python      Beginner    10/09/2023
1      Douglas Tucker                 Python       Master     11/09/2023
2      Travis Walters                   Java  Intermediate    12/09/2023
3    Nathaniel Harris        Web development      Advanced    13/09/2023
5        Tonya Carter  Ai & machine learning      Beginner    14/09/2023

In [21]:
def certificate_generator(name,courseName,CourseLevel,FormattedDate):


  pdf_file_name = "/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)/certificates/" + name + "-" + courseName + "-" + CourseLevel + ".pdf"

  # storing the canvas inside
  # creating a canvas object from reportlab import and inserting our certificates FOLDER path into it.
  # canvas needs 2 inputs
  # 1st input - where to store it
  # 2nd input - what size

  c = canvas.Canvas(pdf_file_name, pagesize = landscape(A4))


  # drawImage() needs 5 inputs
  # 1st input --> image --> the thing we are drawing
  # 2nd input --> x-axis (coordinate 0)
  # 3rd input --> y-axis (coordinate 0)
  # 4th input --> width --> A4[1] (STANDARD)
  # 5th input --> height --> A4[0] (STANDARD)
  c.drawImage("/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)/certificate_template.jpg",0,0, width = A4[1], height = A4[0])

  c.save()

In [22]:
certificate_generator("Jivah" , "Python" , "Beginner" , "12/07/2024")
certificate_generator("Kate" , "Python" , "Master" , "30/06/2024")

Version 2

In [23]:
def certificate_generator(name,courseName,CourseLevel,FormattedDate):


  pdf_file_name = "/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)/certificates/" + name + "-" + courseName + "-" + CourseLevel + ".pdf"

  c = canvas.Canvas(pdf_file_name, pagesize = landscape(A4))

  c.drawImage("/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)/certificate_template.jpg",0,0, width = A4[1], height = A4[0])

  print('---------------------------')
  center_x = c._pagesize[0] /2 # middle of the A4 page

  print("Full width of the A4 is : ", c._pagesize[0])
  print("Center of the A4 x-axis is ; " , center_x) # center A4 canvas size (x-axis)

  print('---------------------------')

  center_y = c._pagesize[1] /2

  print("Full height of the A4 is : ", c._pagesize[1])
  print("Center of the A4 y-axis is : " , center_y)

  c.save()

In [24]:
certificate_generator("Ali" , "Python" , "Beginner" , "12/07/2024")
certificate_generator("Abu" , "Python" , "Master" , "30/06/2024")

---------------------------
Full width of the A4 is :  841.8897637795277
Center of the A4 x-axis is ;  420.94488188976385
---------------------------
Full height of the A4 is :  595.2755905511812
Center of the A4 y-axis is :  297.6377952755906
---------------------------
Full width of the A4 is :  841.8897637795277
Center of the A4 x-axis is ;  420.94488188976385
---------------------------
Full height of the A4 is :  595.2755905511812
Center of the A4 y-axis is :  297.6377952755906

Version 3

In [25]:
def certificate_generator(name,courseName,CourseLevel,FormattedDate):


  pdf_file_name = "/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)/certificates/" + name + "-" + courseName + "-" + CourseLevel + ".pdf"

  c = canvas.Canvas(pdf_file_name, pagesize = landscape(A4))

  c.drawImage("/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)/certificate_template.jpg",0,0, width = A4[1], height = A4[0])

  center_x = c._pagesize[0] / 2
  center_y = c._pagesize[1] / 2

  # Name
  c.setFont('Lora-Bold' , 30)
  c.drawCentredString(center_x , center_y - 46, name)

  # Coursename and courseLevel
  c.setFont('Lora-Bold' , 28)
  c.drawCentredString(center_x  , center_y - 105, courseName + " - " + CourseLevel)

  # Date
  c.setFont('Lora-Bold' , 24)
  c.drawCentredString(center_x + 190  , center_y - 170, FormattedDate)

  # Cert ID
  cert_id = "Cert ID: " + str(int(pd.Timestamp.now().timestamp()))
  c.setFont('Lora-Regular' , 12)
  c.drawCentredString(center_x + 266 , center_y - 230, cert_id.upper())

  c.save()

In [26]:
str(int(pd.Timestamp.now().timestamp()))

'1781498237'

In [27]:
print(pd.Timestamp.now())
print(pd.Timestamp.now().timestamp()) # Unix timestamp (number of seconds since January 1 1970)
print(int(pd.Timestamp.now().timestamp())) # removing the floating point

2026-06-15 04:37:18.723537
1781498238.723726
1781498238

In [28]:
certificate_generator("Jenny" , "Python" , "Beginner" , "12/07/2024")
certificate_generator("Harry" , "Python" , "Master" , "30/06/2024")

Version 4

In [29]:
def certificate_generator(name,courseName,CourseLevel,FormattedDate):


  pdf_file_name = "/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)/certificates/" + name + "-" + courseName + "-" + CourseLevel + ".pdf"

  c = canvas.Canvas(pdf_file_name, pagesize = landscape(A4))

  c.drawImage("/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)/certificate_template.jpg",0,0, width = A4[1], height = A4[0])

  center_x = c._pagesize[0] / 2
  center_y = c._pagesize[1] / 2

  # Name
  c.setFont('Lora-Bold' , 30)
  c.drawCentredString(center_x , center_y - 46, name)

  # Coursename and courseLevel
  c.setFont('Lora-Bold' , 28)
  c.drawCentredString(center_x  , center_y - 105, courseName + " - " + CourseLevel)

  # Date
  c.setFont('Lora-Bold' , 24)
  c.drawCentredString(center_x + 190  , center_y - 170, FormattedDate)

  # Cert ID
  cert_id = "Cert ID: " + str(int(pd.Timestamp.now().timestamp()))
  c.setFont('Lora-Regular' , 12)
  c.drawCentredString(center_x + 266 , center_y - 230, cert_id.upper())

  c.save()

In [30]:
df

                  Name                 Course   CourseLevel FormattedDate
0   Christy Cunningham                 Python      Beginner    10/09/2023
1       Douglas Tucker                 Python       Master     11/09/2023
2       Travis Walters                   Java  Intermediate    12/09/2023
3     Nathaniel Harris        Web development      Advanced    13/09/2023
5         Tonya Carter  Ai & machine learning      Beginner    14/09/2023
6           Erik Smith     Mobile development      Beginner    15/09/2023
7   Kristopher Johnson                 Python      Beginner    16/09/2023
9          Robert Buck                 Python       Master     17/09/2023
10     Joseph Mcdonald                   Java  Intermediate    18/09/2023
11       Jerome Abbott        Web development      Advanced    19/09/2023
12       William Riley  Ai & machine learning      Beginner    20/09/2023

In [31]:
# df.iterrows (loopable)
# gives 2 items  (index, item(row))

for index , row in df.iterrows():
  print(index)

0
1
2
3
5
6
7
9
10
11
12

In [32]:
for index , row in df.iterrows():
  print(row)
  print('----------------------------')
  print()

Name             Christy Cunningham
Course                       Python
CourseLevel                Beginner
FormattedDate            10/09/2023
Name: 0, dtype: object
----------------------------

Name             Douglas Tucker
Course                   Python
CourseLevel             Master
FormattedDate        11/09/2023
Name: 1, dtype: object
----------------------------

Name             Travis Walters
Course                     Java
CourseLevel        Intermediate
FormattedDate        12/09/2023
Name: 2, dtype: object
----------------------------

Name             Nathaniel Harris
Course            Web development
CourseLevel              Advanced
FormattedDate          13/09/2023
Name: 3, dtype: object
----------------------------

Name                      Tonya Carter
Course           Ai & machine learning
CourseLevel                   Beginner
FormattedDate               14/09/2023
Name: 5, dtype: object
----------------------------

Name                     Erik Smith
Course           Mobile development
CourseLevel                Beginner
FormattedDate            15/09/2023
Name: 6, dtype: object
----------------------------

Name             Kristopher Johnson
Course                       Python
CourseLevel                Beginner
FormattedDate            16/09/2023
Name: 7, dtype: object
----------------------------

Name             Robert Buck
Course                Python
CourseLevel          Master
FormattedDate     17/09/2023
Name: 9, dtype: object
----------------------------

Name             Joseph Mcdonald
Course                      Java
CourseLevel         Intermediate
FormattedDate         18/09/2023
Name: 10, dtype: object
----------------------------

Name               Jerome Abbott
Course           Web development
CourseLevel             Advanced
FormattedDate         19/09/2023
Name: 11, dtype: object
----------------------------

Name                     William Riley
Course           Ai & machine learning
CourseLevel                   Beginner
FormattedDate               20/09/2023
Name: 12, dtype: object
----------------------------

In [33]:
for index , row in df.iterrows():
  certificate_generator(row['Name'] , row['Course'] , row['CourseLevel'], row['FormattedDate'])

print(str(len(df)) + " certificates generated successfully! ")

11 certificates generated successfully!

In [ ]:
# 1. Configure your identity
!git config --global user.name "Jivahloshini08"
# Replace with the email address linked to your GitHub account
!git config --global user.email "loshini239@gmail.com"

# 2. Target your project folder path in Google Drive
%cd "/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)"

# 3. Initialize Git and link it to your GitHub Repository
!git init

# 4. PASTE YOUR FINE-GRAINED TOKEN DIRECTLY INSIDE THE URL BELOW
!git remote add origin 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

# 5. Package and upload all your files
!git branch -M main
!git add .
!git commit -m "Uploaded notebook, templates, datasets, and fonts (cert generator)"
!git push -u origin main